site_name: Inlets
site_description: Inlets Secure Tunnels From Dev to Cloud
site_author: OpenFaaS Ltd
site_url: https://docs.inlets.dev/

# Repository
repo_name: inlets/inlets
repo_url: https://github.com/inlets
edit_uri: ""

copyright: |
  Copyright &copy; 2021 OpenFaaS Ltd
theme:
  name: material
  # custom_dir: docs/theme
  logo: images/logo.svg

  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

  font:
    text: Roboto, Helvetica
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.sections
    # - toc.integrate
    # - navigation.instant

  include_search_page: false
  search_index_only: true

  language: en

  # favicon: images/favicon.ico
  logo: images/logo.svg

extra:
  search:
    languages: "en"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inlets/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/inletsdev

plugins:
  - search
  
markdown_extensions:
  - attr_list
  - md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Overview:
      - Introduction: index.md
      - FAQ: /reference/faq/
  - Tutorials:
      - Create a manual HTTP tunnel server: /tutorial/manual-http-server/
      - Create an automated HTTP tunnel server: /tutorial/automated-http-server/
      - Dual TCP and HTTP tunnels: /tutorial/dual-tunnels/
      - Community tutorials: /tutorial/community/
  - Tutorials for TCP tunnels:
      - Run Caddy on ap private network: /tutorial/caddy-http-tunnel/
      - Tunnel SSH: /tutorial/ssh-tcp-tunnel/
      - Tunnel Postgresql: /tutorial/postgresql-tcp-tunnel/
  - Kubernetes:
      - Kubernetes Ingress: /tutorial/kubernetes-ingress/
      - Kubernetes API Server: /tutorial/kubernetes-api-server/
      - Istio Gateway: /tutorial/istio-gateway/
  - Reference:
      - Overview: reference.md
      - Inlets Operator: /reference/inlets-operator/
      - inletsctl: /reference/inletsctl/
      - Monitoring and metrics: /tutorial/monitoring-and-metrics/

extra:
  analytics:
    provider: google
    property: UA-60759269-5
    anonymize_ip: true
